#!/bin/bash
#
# S.W.A.D PROPRIETARY AND CONFIDENTIAL
# __________________
# 
# Copyright (c) 2015-2019 S.W.A.D All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of S.W.A.D and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to S.W.A.D
# and its suppliers, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material,
# in whole or in part, is strictly forbidden unless prior written
# permission is obtained from S.W.A.D.
#


JAVA_HOME=/opt/local/jdk1.8.0_131
JAVA_EXEC=$JAVA_HOME/bin/java

NTA_BASE_HOME=$(dirname $(cd $(dirname "${BASH_SOURCE-$0}"); pwd))

# Generate KELL_SELF script
# echo "kill -9 $$" > $NTA_BASE_HOME/bin/kill_self

# JVM Memory Control
# JAVA_OPTS="$JAVA_OPTS -XX:MaxMetaspaceSize=128m -Xmx8192M -XX:MinHeapFreeRatio=30 -XX:MaxHeapFreeRatio=50"
# JAVA_OPTS="$JAVA_OPTS -XX:OnOutOfMemoryError=$KILL_SELF"

# Debug configuration

# JMX_HOST=
# JMX_PORT=18080
# REMOTE_DEBUG_PORT=12345

# JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=$JMX_HOST -Dcom.sun.management.jmxremote.port=$JMX_PORT -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
# JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,address=$REMOTE_DEBUG_PORT,server=y,suspend=n"

#
# Run java process
#
exec $JAVA_EXEC $JAVA_OPTS -Dlog4j.configuration=$NTA_BASE_HOME/conf/log4j.properties -jar $NTA_BASE_HOME/lib/nta-web-base.jar --spring.config.location=file:/opt/nta/web/base/conf/application.properties
